### ISSUE TITLE
tilt specs fail with markaby 0.7.1

### ISSUE THREAD

**Issue by graaff** [markaby/markaby#29]
When I try to run the specs for markaby 0.7.1 I'm getting the following failures (with tilt 1.3.2):

```
1)
'Markaby::Tilt templates should retrieve a Tilt::MarkabyTemplate when calling Tilt['hello.mab']' FAILED
expected: Markaby::Tilt::Template,
     got: Tilt::MarkabyTemplate (using ==)
./spec/markaby/tilt_spec.rb:68:
/usr/lib64/ruby/1.8/timeout.rb:53:in `timeout'

2)
'Markaby::Tilt templates should return a new instance of the implementation class (when calling Tilt.new)' FAILED
expected #<Tilt::MarkabyTemplate:0x7f369529c340 @compiled_method={}, @options={}, @reader=#<Proc:0x00007f369339ce68@/usr/lib64/ruby/gems/1.8/gems/tilt-1.3.2/lib/tilt/template.rb:67>, @line=1, @file="./spec/markaby/tilt/markaby.mab", @data="text \"hello from markaby!\"\n", @default_encoding=nil> to be a kind of Markaby::Tilt::Template
./spec/markaby/tilt_spec.rb:72:
/usr/lib64/ruby/1.8/timeout.rb:53:in `timeout'
```

I've also checked HEAD (e62052d90bb56536189bc7e0d755200d9253c5a8) since I noticed some tilt-related changes, but there I get a different failure:

```
./spec/markaby/tilt_spec.rb:4: uninitialized constant Markaby::Tilt (NameError)
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/lib/spec/runner/example_group_runner.rb:15:in `load'
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/lib/spec/runner/example_group_runner.rb:15:in `load_files'
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/lib/spec/runner/example_group_runner.rb:14:in `each'
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/lib/spec/runner/example_group_runner.rb:14:in `load_files'
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/lib/spec/runner/options.rb:134:in `run_examples'
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/lib/spec/runner/command_line.rb:9:in `run'
    from /usr/lib64/ruby/gems/1.8/gems/rspec-1.3.2/bin/spec:5
```

**Comment by smtlaissezfaire** [comment]
Closing this. Re-open if tilt still isn't working.
